# Generated by Django 5.0 on 2024-01-06 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True, db_comment='Date and time the order was created')),
                ('expirationDate', models.DateTimeField(db_comment='Date when the order is no longer valid')),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('FU', 'Fulfilled'), ('EX', 'Expired')], default='OP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountRemaining', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('KG', 'Kilograms'), ('LB', 'Pounds'), ('GR', 'Grams'), ('PK', 'Packages'), ('PC', 'Pieces'), ('LI', 'Liters'), ('GA', 'Gallons')], default='PC', max_length=2)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbankapi.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbankapi.order')),
            ],
        ),
    ]
