# Generated by Django 5.0 on 2024-02-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbankapi', '0002_alter_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
        migrations.AddField(
            model_name='order',
            name='fromOrganization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderFromOrganization', to='foodbankapi.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='toOrganization',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='orderToOrganization', to='foodbankapi.organization'),
            preserve_default=False,
        ),
    ]
