# Generated by Django 5.0 on 2024-01-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbankapi', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('GA', 'Gallons'), ('GR', 'Grams'), ('KG', 'Kilograms'), ('LI', 'Liters'), ('PK', 'Packages'), ('PC', 'Pieces'), ('LB', 'Pounds')], default='PC', max_length=2),
        ),
    ]
