# Generated by Django 5.0 on 2024-02-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbankapi', '0004_alter_orderitem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BE', 'Beverages'), ('BA', 'Baking'), ('BR', 'Breads'), ('CH', 'Cheeses'), ('DE', 'Desserts'), ('DR', 'Dry goods'), ('EG', 'Eggs'), ('FA', 'Fats'), ('FZ', 'Frozen foods'), ('FR', 'Fruits'), ('PR', 'Proteins'), ('SE', 'Seafood'), ('SP', 'Spices'), ('SW', 'Sweets'), ('UN', 'Uncategorized'), ('VE', 'Vegetables')], default='UN', max_length=2, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
