# Generated by Django 5.0 on 2024-02-01 10:49

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbankapi', '0005_organization_alter_item_category_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=64, verbose_name='state')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postalCode', models.CharField(max_length=16, verbose_name='postal code')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('DI', 'Distributor'), ('SU', 'Supplier')], default='DI', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodbankapi.address'),
        ),
    ]
