export const categoryChoices = {
    "":"",
    "Beverages":"BE",
    "Baking":"BA",
    "Breads":"BR",
    "Dairy":"DA",
    "Dry goods":"DR",
    "Fats":"FA",
    "Frozen foods":"FZ",
    "Fruits":"FR",
    "Proteins":"PR",
    "Seafood":"SE",
    "Spices":"SP",
    "Vegetables":"VE",
}