export const categoryChoices = [
    "",
    "Beverages",
    "Baking",
    "Breads",
    "Dairy",
    "Dry goods",
    "Fats",
    "Frozen foods",
    "Fruits",
    "Proteins",
    "Seafood",
    "Spices",
    "Vegetables",
]