export const foodsByCategory = {
    "": [],
    "Beverages": [
        "Apple juice",
        "Coffee",
        "Cranberry juice",
        "Orange juice",
        "Tea",
    ],
    "Baking": [
        "Active dry yeast",
        "All-purpose flour",
        "Baking powder",
        "Baking soda",
        "Brown sugar",
        "Cornmeal",
        "Eggs",
        "Granulated sugar",
        "Honey",
        "Maple Syrup",
        "Molasses",
        "Powdered sugar",
        "Salt",
        "Whole-wheat flour",
    ],
    "Breads and Grains": [
        "Bagels",
        "Brown rice",
        "Crackers",
        "Gluten-free bread",
        "Macaroni",
        "Oatmeal",
        "Rice noodles",
        "Rolls",
        "Sandwich bread",
        "Spaghetti",
        "White rice",
    ],
    "Dairy": [
        "Butter",
        "Cheese",
        "Cream Cheese",
        "Fat free milk",
        "Lactose-free milk",
        "Powdered Milk",
        "Sour Cream",
        "Whipping cream",
        "Whole Milk",
    ],
    "Dry goods": [
        "Canned beans",
        "Canned beef",
        "Canned chicken",
        "Canned chickpeas",
        "Canned pineapple",
        "Canned tomatoes",
        "Canned tuna",
        "Coconut milk",
        "Dry beans",
        "Dry chickpeas",
        "Jelly",
        "Peanut butter",
        "Tomato paste",
    ],
    "Fats": [
        "Canola oil",
        "Mayonnaise",
        "Olive oil",
        "Shortening",
        "Vegetable oil",
    ],
    "Frozen foods": [
        "Corn",
        "Green beans",
        "Mixed berries",
        "Mixed Vegetables",
        "Peas",
        "Raspberries",
        "Soup mix",
        "Spinach",
        "Strawberries",
    ],
    "Fruits": [
        "Apple",
        "Banana",
        "Blueberry",
        "Orange",
        "Strawberry",
        "Watermelon"
    ],
    "Proteins": [
        "Beef roast",
        "Chicken breast",
        "Chicken cutlets",
        "Ground beef",
        "Pork chop",
        "Pork roast",
        "Whole chicken",
    ],
    "Seafood": [
        "Salmon filets",
        "Smoked salmon",
    ],
    "Spices": [
        "Allspice",
        "Basil",
        "Black Pepper",
        "Cinnamon",
        "Cloves", 
        "Ginger",
        "Oregano",
        "Red pepper flakes",
    ],
    "Vegetables": [
        "Bell pepper",
        "Broccoli",
        "Cauliflower",
        "Cucumber",
        "Lettuce",
        "Onion",
        "Tomato",
        "Zucchini",
    ],
}